-- ============================================================
-- 红霞影剧院 (Sunset Playhouse) — Supabase Schema v2
-- 在 Supabase SQL Editor 中全选执行即可
-- ============================================================

-- ============================
-- 1. STORAGE BUCKETS
-- ============================

-- 头像桶
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

-- 明信片 & 物料图片桶（共用）
insert into storage.buckets (id, name, public)
values ('postcards', 'postcards', true)
on conflict (id) do nothing;

-- ============================
-- 2. STORAGE RLS POLICIES
-- ============================

-- avatars: 已认证用户可上传
drop policy if exists "Avatar insert" on storage.objects;
create policy "Avatar insert" on storage.objects
  for insert with check (bucket_id = 'avatars' and auth.role() = 'authenticated');

-- avatars: 所有人可读
drop policy if exists "Avatar select" on storage.objects;
create policy "Avatar select" on storage.objects
  for select using (bucket_id = 'avatars');

-- postcards: 已认证用户可上传
drop policy if exists "Postcard insert" on storage.objects;
create policy "Postcard insert" on storage.objects
  for insert with check (bucket_id = 'postcards' and auth.role() = 'authenticated');

-- postcards: 所有人可读
drop policy if exists "Postcard select" on storage.objects;
create policy "Postcard select" on storage.objects
  for select using (bucket_id = 'postcards');

-- postcards: 所有人可更新
drop policy if exists "Postcard update" on storage.objects;
create policy "Postcard update" on storage.objects
  for update using (bucket_id = 'postcards' and auth.role() = 'authenticated');

-- postcards: 所有者可删除
drop policy if exists "Postcard delete" on storage.objects;
create policy "Postcard delete" on storage.objects
  for delete using (bucket_id = 'postcards' and auth.role() = 'authenticated');

-- ============================
-- 3. TABLES
-- ============================

-- 3.1 明信片
create table if not exists postcards (
  id         bigint primary key,
  user_id    uuid references auth.users not null,
  sender     text not null,
  content    text not null,
  image_url  text,
  image_urls text,
  date       text not null,
  created_at timestamptz default now()
);
alter table postcards enable row level security;

-- 3.2 物料交流
create table if not exists crafts (
  id        bigint primary key,
  user_id   uuid references auth.users not null,
  author    text not null,
  title     text not null,
  img       text,
  "desc"    text not null,
  date      text not null,
  created_at timestamptz default now()
);
alter table crafts enable row level security;

-- 3.3 明信片点赞
create table if not exists postcard_likes (
  id          bigint generated by default as identity primary key,
  postcard_id bigint references postcards(id) on delete cascade not null,
  user_id     uuid references auth.users not null,
  created_at  timestamptz default now(),
  unique(postcard_id, user_id)
);
alter table postcard_likes enable row level security;

-- 3.4 明信片评论
create table if not exists postcard_comments (
  id          bigint generated by default as identity primary key,
  postcard_id bigint references postcards(id) on delete cascade not null,
  user_id     uuid references auth.users,
  author      text not null,
  content     text not null,
  created_at  timestamptz default now()
);
alter table postcard_comments enable row level security;

-- 3.5 物料点赞
create table if not exists craft_likes (
  id         bigint generated by default as identity primary key,
  craft_id   bigint references crafts(id) on delete cascade not null,
  user_id    uuid references auth.users not null,
  created_at timestamptz default now(),
  unique(craft_id, user_id)
);
alter table craft_likes enable row level security;

-- 3.6 物料评论
create table if not exists craft_comments (
  id         bigint generated by default as identity primary key,
  craft_id   bigint references crafts(id) on delete cascade not null,
  user_id    uuid references auth.users,
  author     text not null,
  content    text not null,
  created_at timestamptz default now()
);
alter table craft_comments enable row level security;

-- 3.7 通知
create table if not exists notifications (
  id           bigint generated by default as identity primary key,
  recipient_id uuid references auth.users not null,
  type         text not null,
  actor        text not null,
  target_id    bigint,
  extrainfo    text default '',
  "read"       boolean default false,
  created_at   timestamptz default now()
);
alter table notifications enable row level security;

-- 3.8 巡演心情
create table if not exists stop_moods (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users not null,
  stop_id    text not null,
  city       text not null,
  moods      text not null,
  created_at timestamptz default now(),
  unique(user_id, stop_id)
);
alter table stop_moods enable row level security;

-- 3.9 打卡记录
create table if not exists checkins (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users not null,
  stop_id    text not null,
  city       text not null,
  created_at timestamptz default now(),
  unique(user_id, stop_id)
);
alter table checkins enable row level security;

-- 3.10 成就
create table if not exists achievements (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users not null,
  ach_id     text not null,
  created_at timestamptz default now(),
  unique(user_id, ach_id)
);
alter table achievements enable row level security;

-- ============================
-- 4. TABLE RLS POLICIES
-- ============================

-- postcards: 所有人可读
drop policy if exists "Postcards select" on postcards;
create policy "Postcards select" on postcards
  for select using (true);

-- postcards: 已认证用户可插入
drop policy if exists "Postcards insert" on postcards;
create policy "Postcards insert" on postcards
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

-- postcards: 所有者可删除
drop policy if exists "Postcards delete" on postcards;
create policy "Postcards delete" on postcards
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- crafts: 所有人可读
drop policy if exists "Crafts select" on crafts;
create policy "Crafts select" on crafts
  for select using (true);

-- crafts: 已认证用户可插入
drop policy if exists "Crafts insert" on crafts;
create policy "Crafts insert" on crafts
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

-- crafts: 所有者可删除
drop policy if exists "Crafts delete" on crafts;
create policy "Crafts delete" on crafts
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- postcard_likes: 所有人可读
drop policy if exists "Postcard likes select" on postcard_likes;
create policy "Postcard likes select" on postcard_likes
  for select using (true);

-- postcard_likes: 已认证可增删
drop policy if exists "Postcard likes insert" on postcard_likes;
create policy "Postcard likes insert" on postcard_likes
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Postcard likes delete" on postcard_likes;
create policy "Postcard likes delete" on postcard_likes
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- postcard_comments: 所有人可读
drop policy if exists "Postcard comments select" on postcard_comments;
create policy "Postcard comments select" on postcard_comments
  for select using (true);

-- postcard_comments: 已认证可插入
drop policy if exists "Postcard comments insert" on postcard_comments;
create policy "Postcard comments insert" on postcard_comments
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

-- postcard_comments: 所有者可删除
drop policy if exists "Postcard comments delete" on postcard_comments;
create policy "Postcard comments delete" on postcard_comments
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- craft_likes: 所有人可读
drop policy if exists "Craft likes select" on craft_likes;
create policy "Craft likes select" on craft_likes
  for select using (true);

-- craft_likes: 已认证可增删
drop policy if exists "Craft likes insert" on craft_likes;
create policy "Craft likes insert" on craft_likes
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Craft likes delete" on craft_likes;
create policy "Craft likes delete" on craft_likes
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- craft_comments: 所有人可读
drop policy if exists "Craft comments select" on craft_comments;
create policy "Craft comments select" on craft_comments
  for select using (true);

-- craft_comments: 已认证可插入
drop policy if exists "Craft comments insert" on craft_comments;
create policy "Craft comments insert" on craft_comments
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

-- craft_comments: 所有者可删除
drop policy if exists "Craft comments delete" on craft_comments;
create policy "Craft comments delete" on craft_comments
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- notifications: 仅收件人可读写
drop policy if exists "Notifications select" on notifications;
create policy "Notifications select" on notifications
  for select using (auth.role() = 'authenticated' and auth.uid() = recipient_id);

drop policy if exists "Notifications insert" on notifications;
create policy "Notifications insert" on notifications
  for insert with check (auth.role() = 'authenticated');

drop policy if exists "Notifications update" on notifications;
create policy "Notifications update" on notifications
  for update using (auth.role() = 'authenticated' and auth.uid() = recipient_id);

-- stop_moods: 所有人可读
drop policy if exists "Stop moods select" on stop_moods;
create policy "Stop moods select" on stop_moods
  for select using (true);

-- stop_moods: 已认证可增删改
drop policy if exists "Stop moods insert" on stop_moods;
create policy "Stop moods insert" on stop_moods
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Stop moods delete" on stop_moods;
create policy "Stop moods delete" on stop_moods
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Stop moods update" on stop_moods;
create policy "Stop moods update" on stop_moods
  for update using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- checkins: 已认证可增删查
drop policy if exists "Checkins select" on checkins;
create policy "Checkins select" on checkins
  for select using (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Checkins insert" on checkins;
create policy "Checkins insert" on checkins
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);

drop policy if exists "Checkins delete" on checkins;
create policy "Checkins delete" on checkins
  for delete using (auth.role() = 'authenticated' and auth.uid() = user_id);

-- achievements: 所有人可读
drop policy if exists "Achievements select" on achievements;
create policy "Achievements select" on achievements
  for select using (true);

-- achievements: 已认证可插入
drop policy if exists "Achievements insert" on achievements;
create policy "Achievements insert" on achievements
  for insert with check (auth.role() = 'authenticated' and auth.uid() = user_id);
